// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOZxWhioy_-AK5EIYHl0v-Gc1ArX1VZPg',
    appId: '1:111213052809:web:d9362454cfc00ac72b9758',
    messagingSenderId: '111213052809',
    projectId: 'chat-app-53f77',
    authDomain: 'chat-app-53f77.firebaseapp.com',
    storageBucket: 'chat-app-53f77.appspot.com',
    measurementId: 'G-TK8MBTX13K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUZ3_meIfFupIVATj8scJ5p2sG9cYEbjg',
    appId: '1:111213052809:android:1c22850b81279f972b9758',
    messagingSenderId: '111213052809',
    projectId: 'chat-app-53f77',
    storageBucket: 'chat-app-53f77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGKG10PqJTtN3Cq6lxoxJJWrXP8-ssuPk',
    appId: '1:111213052809:ios:0473d51e74d234c02b9758',
    messagingSenderId: '111213052809',
    projectId: 'chat-app-53f77',
    storageBucket: 'chat-app-53f77.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGKG10PqJTtN3Cq6lxoxJJWrXP8-ssuPk',
    appId: '1:111213052809:ios:43e1b576a257147f2b9758',
    messagingSenderId: '111213052809',
    projectId: 'chat-app-53f77',
    storageBucket: 'chat-app-53f77.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
